# https://codeclimate.com/github/newcontext-oss/kitchen-terraform
exclude_patterns:
  - assets/
  - bin/
  - certs/
  - coverage/
  - doc/
  - examples/
  - tmp/
plugins:
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - "ruby"
  fixme:
    enabled: true
  flog:
    enabled: true
  git-legal:
    enabled: true
  markdownlint:
    enabled: true
  reek:
    enabled: true
  rubocop:
    enabled: true
  structure:
    enabled: true
version: 2
